# Generated by Django 5.0.6 on 2024-05-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('is_expert', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='OurFeedback',
        ),
    ]
