"""
Django settings for mainproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i16m)os08v+f$^!d0_)q(t=a@$+o(4+p2q-ysx@&hpc1ej(wvt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "mario.apps.MarioConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mainproject.urls'

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
]

CHANNEL_LAYERS = {
    'default': {
        # 'BACKEND': 'channels.layers.InMemoryChannelLayer',  # または Redis を使用する場合は適切な設定
        'BACKEND': 'channels_redis.core.RedisChannelLayer', #本番環境用のやつ、やりたくねぇ
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mainproject.wsgi.application'
ASGI_APPLICATION = 'mainproject.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'mario' / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']

CODE_TEXTS = {
    '0': 'Small Mario ：',
    '1': 'Big Mario ：',
    '2': 'Fire Mario ：',
    '3': 'Fish ：',
    '4': 'Nokonoko ：',
    '5': 'Kuribo ：',
    '6': 'Hatena Block ：',
    '7': 'Kinoko ：',
    '8': 'Pipe ：',
    '9': 'P Flower ：',
    '10': 'Togezo ：',
    '11': 'Star ：',
    '12': 'Hummer Bros ：',
    '13': 'Hummer ：',
    '14': 'Blooper ：',
    '15': 'Kuppa ：',
    '16': 'Killer ：',
    '17': 'Patapata ：',
    '18': 'Met ：',
    '19': 'Scaffold Normal ：',
    '20': 'Scaffold Sky ：',
    '21': 'Scaffold Kuppa ：',
    '22': 'Fire Ball ：',
    '23': 'Fire Stick ：',
    '24': 'Fire Kuppa ：',
    '25': 'Lava ：',
    '26': 'Elevator ：',
    '27': 'Kuppa Hummer ：',
}